### ISSUE TITLE
500 server side on deployment creation if module doesn't exist or user doesn't have access to it

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#328]
The server should return something from 4xx error family. 

Below the error when module exists, but user doesn't have access to it.

```
send: b'POST /api/deployment HTTP/1.1\r\nHost: nuvla.io\r\nUser-Agent: python-requests/2.23.0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json\r\nConnection: keep-alive\r\nCookie: com.sixsq.nuvla.cookie=eyJhbGciOiJSUzI1NiJ9.eyJ1c2VyLWlkIjoidXNlci9lNWJlNmNjMS02OTQyLTQ5OTEtYWNmNC03ZDVjZjk1YjljYzYiLCJjbGFpbXMiOiJncm91cC9udXZsYS1hbm9uIGdyb3VwL251dmxhLXVzZXIgZ3JvdXAvc2l4c3EtZGV2cyBzZXNzaW9uL2E0MjQ4MGM5LWFlZWUtNDQxMS1hN2Y4LTU4NmJiZDI4OTUzOCIsInNlc3Npb24iOiJzZXNzaW9uL2E0MjQ4MGM5LWFlZWUtNDQxMS1hN2Y4LTU4NmJiZDI4OTUzOCIsImNsaWVudC1pcCI6IjEwLjI1NS4wLjIiLCJleHAiOjE1ODQ2NTIwOTd9.xDOiltcR34ZBBXmAgZbL2JWJ9eJm6ebHfKcpjskVg5_rXHSahOkIFwr_k9DYu5heFBaBgq8OOLly6EAyMyi3KQQ5gcTjfMTdzs1gf4aNBUAlU-MbVZ7wT44Ba45QIiDAM1-z6MhQLIlBCEZnNmnuLfUw114S0YoQzn3bzizMJdEQ84jlgu641W_aMpBG9ysAEmRhBoTuS22ATL4XsGqlOPKL7ZI3O680zAA8zK2n9MfAPD-adlGmzRwzZMq0IIgOIOKL4aHCobFTBiBGQogV5UJcO3nIqXGe3PUf9-RoTyzpWDM-f68gjvSDdZRvJL4w10PU_X1duWGbs3bfelMy8Q\r\nContent-Length: 67\r\nContent-Type: application/json\r\n\r\n'
send: b'{"module": {"href": "module/80486e74-1afc-46a5-9317-d5ee8c83ffd0"}}'
reply: 'HTTP/1.1 500 Internal Server Error\r\n'
header: Content-Length: 132
header: Content-Type: application/json; charset=utf-8
header: Date: Thu, 12 Mar 2020 21:08:17 GMT
header: Server: Aleph/0.4.4
DEBUG:urllib3.connectionpool:https://nuvla.io:443 "POST /api/deployment HTTP/1.1" 500 132
Traceback (most recent call last):
  File "/Users/konstan/code/nuvla/python-library/code/src/nuvla/api/api.py", line 342, in _cimi_request
    response.raise_for_status()
  File "/Users/konstan/.virtualenvs/nuvla-api/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://nuvla.io/api/deployment

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./deployment_live_tests.py", line 31, in <module>
    dpl = dpl_api.create(module_id)
  File "/Users/konstan/code/nuvla/python-library/code/src/nuvla/api/resources/deployment.py", line 78, in create
    res = self.nuvla.add(self.resource, module)
  File "/Users/konstan/code/nuvla/python-library/code/src/nuvla/api/api.py", line 456, in add
    return models.CimiResponse(self._cimi_post(resource_id=operation_href, json=data))
  File "/Users/konstan/code/nuvla/python-library/code/src/nuvla/api/api.py", line 365, in _cimi_post
    return self._cimi_request('POST', uri, params=params, json=json, data=data)
  File "/Users/konstan/code/nuvla/python-library/code/src/nuvla/api/api.py", line 355, in _cimi_request
    raise NuvlaError(message, response)
nuvla.api.api.NuvlaError: Unexpected exception thrown: cannot resolve module module/80486e74-1afc-46a5-9317-d5ee8c83ffd0
```

**Comment by 0xbase12** [comment]
The message is pretty clear: `cannot resolve module module/80486e74-1afc-46a5-9317-d5ee8c83ffd0`
If I change the error code to `400` will be fine for you?
