### ISSUE TITLE
on a fresh installation Nuvla fails to put mappings on nuvla-credential and nuvla-nuvlabox-status

### ISSUE THREAD

**Issue by konstan** [nuvla/api-server#433]
On a fresh installation, Nuvla fails to put mappings on `nuvla-credential` and `nuvla-nuvlabox-status` indices with
```
"failed to put mappings on indices [[[nuvla-credential/cnst4VbzRwyffaR4zy_UrA]]], type [_doc]", "cluster
.uuid": "D5qZUOq2SWygty7AOqAAhw", "node.id": "oRKNkg3lRJCGxreCCUHyHA" ,
"stacktrace": ["java.lang.IllegalArgumentException: mapper [acl.edit-acl] of different type, current_type [text], merged_type [keyword]",
"at org.elasticsearch.index.mapper.FieldMapper.doMerge(FieldMapper.java:359) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.TextFieldMapper.doMerge(TextFieldMapper.java:879) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:346) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.FieldMapper.merge(FieldMapper.java:56) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:472) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:443) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:47) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.doMerge(ObjectMapper.java:472) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.RootObjectMapper.doMerge(RootObjectMapper.java:288) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.ObjectMapper.merge(ObjectMapper.java:443) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.RootObjectMapper.merge(RootObjectMapper.java:283) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.Mapping.merge(Mapping.java:91) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.mapper.DocumentMapper.merge(DocumentMapper.java:321) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:283) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:239) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:702) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:324) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:219) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService.access$000(MasterService.java:73) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:151) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:633) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.7.0.jar:7.7.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"]
```
The docs can be created and retrieved from the index. However, queries to `nuvla-credential` fail (500 on PUT) with 

```
"All shards failed for phase: [query]", "cluster.uuid": "D5qZUOq2SWygty7AOqAAhw", "node.id": "oRKNkg3lRJCGxreCCUHyHA" ,
"stacktrace": ["org.elasticsearch.ElasticsearchException$1: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.",
"at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:644) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:307) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:580) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:393) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$100(AbstractSearchAsyncAction.java:68) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:245) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:73) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:59) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:402) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1139) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1248) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1222) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:60) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:56) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:413) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:44) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:692) [elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37) [elasticsearch-7.7.0.jar:7.7.0]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]",
"Caused by: java.lang.IllegalArgumentException: Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [id] in order to load field data by uninverting the inverted index. Note that this can use significant memory.",
"at org.elasticsearch.index.mapper.TextFieldMapper$TextFieldType.fielddataBuilder(TextFieldMapper.java:761) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.fielddata.IndexFieldDataService.getForField(IndexFieldDataService.java:116) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.index.query.QueryShardContext.getForField(QueryShardContext.java:221) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.sort.FieldSortBuilder.build(FieldSortBuilder.java:403) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.sort.SortBuilder.buildSort(SortBuilder.java:159) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.parseSource(SearchService.java:858) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.createContext(SearchService.java:678) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:631) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:428) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.access$200(SearchService.java:135) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395) ~[elasticsearch-7.7.0.jar:7.7.0]",
"at org.elasticsearch.search.SearchService.lambda$runAsync$0(SearchService.java:411) ~[elasticsearch-7.7.0.jar:7.7.0]",
"... 6 more"] }
```

**Comment by konstan** [comment]
using
```
root@nuvla-e9c6dfd7-38d2-43f5-8744-b2dd86c7f55c-k8s-manager-1:~/deployment-k8s/demo# grep image es-deployment.yaml api-deployment.yaml
es-deployment.yaml:          image: nuvla/es:7.7.0.0
api-deployment.yaml:          image: nuvla/api:5.7.0
root@nuvla-e9c6dfd7-38d2-43f5-8744-b2dd86c7f55c-k8s-manager-1:~/deployment-k8s/demo#
```

**Comment by konstan** [comment]
This is the culprit `mapper [acl.edit-acl] of different type, current_type [text], merged_type [keyword]`. Checking.

**Comment by konstan** [comment]
And on `nuvla-nuvlabox-status` - `org.elasticsearch.index.mapper.MapperParsingException: No type specified for field [power-consumption]`

**Comment by konstan** [comment]
The problem is on 5.7.0. 
No problem in 5.6.0.

**Comment by konstan** [comment]
I thought that I might have ES volume left from the installation from `master` over which I was deploying 5.7.0. 
Now re-tried from scratch and the issue with 5.7.0 is indeed there.

```
2020-12-14 10:44:08,826 WARN  - nuvla-nuvlabox-status mapping could not be updated ( 400 ).  {:root_cause [{:type mapper_parsing_exception, :reason No type specified for field [power-consumption]}], :type mapper_parsing_exception, :reason No type specified for field [power-consumption]}
...
2020-12-14 10:44:08,853 WARN  - nuvla-credential mapping could not be updated ( 400 ).  {:root_cause [{:type illegal_argument_exception, :reason mapper [acl.edit-acl] of different type, current_type [text], merged_type [keyword]}], :type illegal_argument_exception, :reason mapper [a
cl.edit-acl] of different type, current_type [text], merged_type [keyword]}
```
Not yet clear where the problem is. All works fine from `master` branch but fails in 5.7.0. My only worry is that it may pass all tests on master and be released, but then break the same way in 5.8.0. While this issue is not affecting nuvla.io (when upgraded), it does affect new installations.

@0xbase12 any obvious reasons I'm missing why this is happening?

**Comment by 0xbase12** [comment]
Stange nothing really changed between 5.7.0 and current master:https://github.com/nuvla/api-server/compare/5.7.0...master

There was an issue of creation of super user because of dynamic load that I fixed before releasing 5.7.0. 

I think I have to ding into to see where is the issue. Will do that in the afternoon

**Comment by 0xbase12** [comment]
The issues releated to updating the mapping is because they exist already and fail to update them. Will do also have a look to that

**Comment by konstan** [comment]
> There was an issue of creation of super user because of dynamic load that I fixed before releasing 5.7.0.

Yep. I noticed that as well.

> The issues releated to updating the mapping is because they exist already and fail to update them.

Strange that this is happening twice. Somehow the "initially" generated mapping is different from the one that is attempted to be created with the second attempt. And while the server loads, it's not possible to log in - w/o any sign of an error on UI nor server-side.

```
2020-12-14 11:32:35,271 INFO  - 200 (14 ms) PUT /api/session [ - ] ?
2020-12-14 11:32:35,848 INFO  - 201 (410 ms) POST /api/session [ - ] ?
2020-12-14 11:32:36,062 INFO  - 200 (15 ms) PUT /api/session [ - ] ?
```

**Comment by konstan** [comment]
@0xbase12 grr... I now see this on master as well. So, definitely, somehow NS load order related.

**Comment by konstan** [comment]
Closing. Fixed by https://github.com/nuvla/api-server/commit/a9a18ab6df4142eeb8dd386e7bece0e159fd0dba
