### ISSUE TITLE
add get-context to nuvlabox_reboot operation

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/api-server#465]
the reboot action only needs the rights to edit the job, otherwise the following will happen in pull mode:

```
2021-03-15 13:25:28,277 - ERROR - base.py:154 - "Operation 'edit' not found."
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/executor.py", line 70, in _process_jobs
    job.set_state('RUNNING')
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/job.py", line 158, in set_state
    self._edit_job('state', state)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/job.py", line 199, in _edit_job
    response = self.api.edit(self.id, {attribute_name: attribute_value})
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 467, in edit
    operation_href = self._cimi_find_operation_href(resource, 'edit')
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 366, in _cimi_find_operation_href
    raise NuvlaResourceOperationNotAvailable(
nuvla.api.api.NuvlaResourceOperationNotAvailable: "Operation 'edit' not found."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/base.py", line 152, in main
    command().execute()
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/base.py", line 144, in execute
    self.do_work()
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/util.py", line 36, in overrided_func
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/executor.py", line 112, in do_work
    self._process_jobs(queue)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/executor.py", line 92, in _process_jobs
    job.update_job(state='FAILED', status_message=status_message, return_code=1)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/job.py", line 190, in update_job
    self._edit_job_multi(attributes)
  File "/usr/local/lib/python3.8/site-packages/nuvla/job/job.py", line 211, in _edit_job_multi
    response = self.api.edit(self.id, attributes)
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 467, in edit
    operation_href = self._cimi_find_operation_href(resource, 'edit')
  File "/usr/local/lib/python3.8/site-packages/nuvla/api/api.py", line 366, in _cimi_find_operation_href
    raise NuvlaResourceOperationNotAvailable(
nuvla.api.api.NuvlaResourceOperationNotAvailable: "Operation 'edit' not found."
```

**Comment by 0xbase12** [comment]
Just for clarification: get-context action allow job-engine (mostly job-engine-lite) to get access to needed documents without being listed in the acl. 

In this case we have to give access to the NB api credential to allow edit the job document.

**Comment by cjdcordeiro** [comment]
> In this case we have to give access to the NB api credential to allow edit the job document.

it should already have. It is the job, from the NB, that edits the job progress and status in Nuvla. If you try an add-ssh-key job this will work

**Comment by cjdcordeiro** [comment]
ok cool so that's the change that needs to happen for reboot as well 👍
